# @package _global_

defaults:
  - _self_
  - generator: sifigan
  - discriminator: univnet
  - train: sifigan
  - data: namine_ritsu

hydra:
  # run:
  #   dir: ./
  # output_subdir: null
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s'
    disable_existing_loggers: false

out_dir:     # Directory to output training results.
seed: 12345  # Seed number for random numbers.
