# General settings.
spk: "Multi"
sample_rate: 48000
spk_list: ["Vo1","S1","ritsu"]
# spk_list: ["Vo1","Vo2","Vo3","A1","A2","A3","Bs1","Bs2","S1","S2","S3","S4","T1","T2","T3","T4","kiritan"]
# spk_list: ["Vo1","Vo2","Vo3"]


# exp tag(for managing experiments)
tag:

################################[###########################
#                DATA PREPARATION SETTING                 #
###########################################################[]

# Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "downloads/jaCapella_ritsu"
db_root_multi_track: "downloads/mt_jaCapella_ritsu"

# Output directory
out_dir: "./data"
out_dir_multi_track: "./data_multitrack"

### Data preparation related settings.
### copied by amaboshi cipher utagoe db recipe

## Song segmentation by silence durations.
# TODO: would be better to split songs by phrasal information in the musical scores
# Split song by silences (in sec)
segmentation_threshold: 0.4
# Min duration for a segment
# note: there could be some exceptions (e.g., the last segment of a song)
segment_min_duration: 5.0
# Force split segments if long silence is found regardless of min_duration
force_split_threshold: 5.0
# Offset correction
# If True, offset is computed in an entire song
# otherwise offset is computed for each segment
global_offset_correction: False
offset_correction_threshold: 0.01
# Time-lag constraints to filter outliers
timelag_allowed_range: [-20, 19]
timelag_allowed_range_rest: [-40, 39]

suppress_start_end_pau: True
start_end_pau_suppression_ratio: 0.2

exclude_too_short_frame: False

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

# HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "../../_common/hed/jp_dev_latest.hed"

timelag_features: defaults
timelag_features_multitrack: multitrack
duration_features: defaults
duration_features_multitrack: multitrack
# acoustic_features: static_deltadelta
acoustic_features: nnsvs_contrib_static_only
acoustic_features_multitrack: multitrack_nnsvs_contrib_static_only

# Parameter trajectory smoothing
# Ref: The NAIST Text-to-Speech System for the Blizzard Challenge 2015
trajectory_smoothing: false
trajectory_smoothing_cutoff: 50

# Base dump norm directory that contains scaler files
base_dump_norm_dir:

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs,
# *_data: data configs (e.g., batch size)

timelag_model: multitrack_timelag_vp_mdn
timelag_train: myconfig
timelag_data: multitrack

duration_model: multitrack_duration_vp_mdn
duration_train: myconfig
duration_data: multitrack

acoustic_model: multitrack_acoustic_nnsvs_world_multi_ar_f0
acoustic_train: myconfig_notuseIL
acoustic_data: multitrack_speaker_world

postfilter_model: postfilter_mgc
postfilter_train: mgc
postfilter_data: myconfig

# Pretrained model dir (leave empty to disable)
pretrained_expdir:
# Pretrained model dir for multi-track training
pretrained_expdir_for_multitrack: 
# pretrained_expdir_for_multitrack: exp/Multi_Vo1S1manual

# Advanced settings for hyperparameter search with Hydra and Optuna.
# https://hydra.cc/docs/plugins/optuna_sweeper/
# NOTE: Don't use spaces for each search space configuration.
# OK: data.batch_size=range(1,16)
# NG: data.batch_size=range(1, 16)
# Example 1: data.batch_size=range(1,16) model.netG.hidden_dim=choice(32,64,128)
# Example 2: train.optim.optimizer.params.lr=interval(0.0001,0.01)
timelag_hydra_optuna_sweeper_args:
timelag_hydra_optuna_sweeper_n_trials: 100
duration_hydra_optuna_sweeper_args:
duration_hydra_optuna_sweeper_n_trials: 100
acoustic_hydra_optuna_sweeper_args:
acoustic_hydra_optuna_sweeper_n_trials: 100

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
# conf/synthesis/synthesis/${synthesis}
# If you use uSFGAN or SiFi-GAN, please set `world_gv_usfgan`
synthesis: world_gv

# latest.pth or best.pth
timelag_eval_checkpoint: best_loss.pth
duration_eval_checkpoint: best_loss.pth
acoustic_eval_checkpoint: best_loss.pth
postfilter_eval_checkpoint: best_loss.pth

###########################################################
#                VOCODER SETTING                          #
###########################################################

# NOTE: conf/parallel_wavegan/${vocoder_model}.yaml must exist.
vocoder_model:
# Pretrained checkpoint path for the vocoder model
# NOTE: if you want to try fine-tuning, please specify the path here
pretrained_vocoder_checkpoint:
# absolute/relative path to the checkpoint
# NOTE: the checkpoint is used for synthesis and packing
# This doesn't have any effect on training
vocoder_eval_checkpoint:
