defaults:
  # Musical/linguistic context -> time-lag (onset fluctuations)
  - timelag: defaults

  # Musical/linguistic context -> phoneme durations
  - duration: defaults

  # Musical/linguistic context -> acoustic parameters (f0, mgc, bap, vuv)
  - acoustic: static_deltadelta

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_


# Common settings for timelag/duration/acoustic features

verbose: 100

utt_list: path/to/list.txt

out_dir: dump

# Number of processes using ProcessPoolExecutor (1 <= max_workers <= 61)
# If null, it will default to the number of processors on the machine.
max_workers: null

# question path used for timelag, duration and acoustic models
question_path:

# Musical/linguistic feature extraction common settings
log_f0_conditioning: true
