defaults:
  # Musical/linguistic context -> acoustic parameters (f0, mgc, bap, vuv)
  - acoustic: static_deltadelta
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

verbose: 100

utt_list:
in_dir:
out_dir:

# Number of processes using ProcessPoolExecutor (1 <= max_workers <= 61)
# If null, it will default to the number of processors on the machine.
max_workers: null

sample_rate: 48000

# Convert mgc to spectrum
mgc2sp: true
